apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tcdc-ip
  namespace: tcdc
  # namespace: monitoring-tools
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: "tcdc.socialhi5.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: tcdc-ip
                port:
                  number: 80